[firebase]
type = "service_account"
project_id = "inspeccion-de-calidad-formimex"
private_key_id = "b54676b0f3aed87215e7cf5907babaa98b00d963"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7zxBolN6d4hcw
nPzYeUIN2Qv9lmr5+FLhlFL8jngHq7ON9GRTp7V/7Ij3Z2lXVCcqFmx6rIavPGFE
+Cu5VXK6xmmj5C9rHIQQ99OyYvy7gdIoDd454B4MJEzBJ6yHVFi5AanzXn8gstVR
7e0U8+niyXpTcW4u0c4XbNhSfqW/8eIQyAWvwOv4iHBtPxvUOr3zcZ5c1+aLn+GG
vWH7uGpghlaal99xde5qpSzJf01sV+hyxN+SO2V9tTfOXpO8N1s0oYMnbOVSNMl8
YxGXOUlKMk02VWuYI5NVhzH+Nn7Sz4jTirQzQXSZXoVEV1wYoPhCkqjYe2P09/4W
qTSR6xO9AgMBAAECggEAKewVqJKagrmmHYbddeDTWs35PDjoVjYVIh9+yrtulZ/B
K83C212TSSPeiwM9Y234dA+fVV7Pjaw3tjKDaBJn0sNZb2kPIKSz4im/ypEIAz7+
T0yRL3AUpPcxXuhhPbAZQeraKeYNEJp6vZgTlNrBeYsp0BiA1NimXVpBi2CT1R1i
KZrIvJvtRqFR3bYFG2u+MZw0rp2LqXOasiHyPoLodaHqA9zEPk7Zp1O8/cA5yZc7
S2RexkTtEcXeV1VanpaKXz15oPimd9nOuFb+32keHMwhM/+WOG3lZFCg1syUr4nr
UtU36P49qA60zayQB7y5qJqw5xAAoZ7l4OwCNI+h7QKBgQDmsZNFaYEALc7MO3MZ
xt/pUej7sqaa3smsxAep7bMWhoZSgvwSgleo8xD3cG7mT9RGngkhl5amYbEQa74s
hb3BbtdqyT7p8P8Tgr4Tnt48xRrYZVuWfksv91pBoAUGud9vZR8VQQvdxbfPWZSp
Mxw9Y2uhd/GXFP0bObcnARcWgwKBgQDQaS6D6Wu5ayrjrp9sKU3aS23kHbPjsXgt
w/Dpw0cgSeKffdgsAek7KCRUHvZEQXAR2g8fzrmeE19gbhgVPweKKrqptfg7u+wd
kc65gUoQtCk34X/FCUDzYozQ4P6bbUHgeY7ejZWq4D6XUj8AuqGqzSgoTEaJoYhX
4qKD/gcYvwKBgQDB0jQfv3KoydPTd6dO4u5BQ5Zx0jl0KPZcdx7RQGqU5FV6gZ5z
lps70WxR2F70leGNqz2UwZ3LEI0JdNyE36D8IbpPd+Gp/9bvd4tnRLUHbbsOUKpQ
mK9nD3T/agiPDB+ToewpmUr0+ydhyKvENLLnSN6m/PU3sGSvOSCOXrYdLQKBgHIR
f7IXaiycKWdgxkUO/luCeW0njLQNCHgUDKIFjcJwbidZW54KlbsZJ3kbUTLelhZP
QYPpQ9LvS36eA3RtgRTweiY1QN6A5qTwjzMdPoqR8RVyyNnxTKlpwST6YKB1Vl8k
aTwKRma2QcvU6kLd42p2y4ny5ZCi5tsjYkvYF85FAoGAWjNTOKLj/o5077EPr12w
l95JRMK/SdrRvTRzPQOhV3F5VGaXX0v/PRJqGIXm9zyWx81Yu1SRkqs72mpVsy4j
p0SN+iVc9mdO1w+kYyL65AVdfecEMLmb/AGRGUsMGK5690R6SlzhWHsvRAFng9dQ
+qtcYKtbBF3xdMDkZNWJLQ4=
-----END PRIVATE KEY-----
"""
client_email = "inspeccion-de-calidad-formimex@inspeccion-de-calidad-formimex.iam.gserviceaccount.com"
client_id = "110022633216644980061"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inspeccion-de-calidad-formimex%40inspeccion-de-calidad-formimex.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
